### DISCUSSION TITLE
Can't submit with anonymous, 401 Unauthorized

### DISCUSSION THREAD

**Discussion by ichenhe** [umputun/remark42#1099] [Q&A] [answered]
I think it might be related to CORS.

I use docker-compose to start the backend, here's my configuration:

```yaml
version: "2"

services:
  remark:
    build: .
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    ports:
      - "3002:8080"

    environment:
      - REMARK_URL=http://remark42.chenhe.me
      - SITE=chenhe_blog
      - SECRET=xxxxxxx
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - DEBUG=true
      - AUTH_ANON=true
      - AUTH_GITHUB_CID=xxxxx
      - AUTH_GITHUB_CSEC=xxxx
    volumes:
      - ./var:/srv/var
```

As you can see, it maps host's 3002 port. I have a Nginx as a reverse proxy to 3002. **There is no extra CORS configuration.**

```
User -> Nginx(:80) -> host(3002) -> docker-remark(8080)
```

My main website is `chenhe.me`, (remark server is `remark42.chenhe.me`), here's my site configuration:

```js
var remark_config = {
        host: "http://remark42.chenhe.me", 
        site_id: 'chenhe_blog',
        components: ['embed'],
};
```

---

The sign in of anonymous is successful, and I get the cookie. But I can't send the comment and it says 'Not authorized'.

From the dev tools, it seems that no cookie have been submitted to the server.

![](https://user-images.githubusercontent.com/10266066/129339653-ddf325ff-98df-485a-badf-689a3288265f.png)
