### DISCUSSION TITLE
Notification email dosn't sended

### DISCUSSION THREAD

**Discussion by ichenhe** [umputun/remark42#1100] [Q&A]
We meet again. I've been reading the document for 4 hours and shouldn't have missed anything 😞 

My backend can send auth email in time so there should be no problem with email settings. But I never got any notification email.

I have been out of ideas about this strange problem, any help is greatly appreciated. 

> By the way,  I'm curious how Remark42 sends notification emails.\
> As I understand, the backend does not store the user's email address. Does the user have to make a subscription explicitly before they can get a reply notification?

Here's my configuration:

<details>
<summary>docker-compose configuration</summary>

```yaml
services:
  remark:
    build: .
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    ports:
      - "3002:8080"

    environment:
      - TIME_ZONE=Asia/Shanghai
      - REMARK_URL=https://remark42.chenhe.me
      - SITE=chenhe-blog
      - SECRET=xxxxxxx
      - SMTP_HOST=mail
      - SMTP_PORT=25
      - ADMIN_SHARED_ID=xxxxx
      - ADMIN_SHARED_EMAIL=xxxxx
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_FROM=do-not-reply@mg.chenhe.me
      - NOTIFY_USERS=email
      - NOTIFY_ADMINS=email
      - NOTIFY_EMAIL_FROM=do-not-reply@mg.chenhe.me
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - DEBUG=true
      - EMOJI=true
      - AUTH_ANON=true
    volumes:
      - ./var:/srv/var

  mailgun: # This should be ok since the auth email can be sent successfully
    image: stevenolen/mailgun-smtp-server
    container_name: "mail"
    hostname: "mail"
    environment:
      - MG_KEY=xxxxxx
      - MG_DOMAIN=mg.chenhe.me
```
</details>

I also checked the logs and there are no warnings or errors -- just some general access log.
