### DISCUSSION TITLE
Sign in issues with Safari's cross-site tracking prevention

### DISCUSSION THREAD

**Discussion by BBaoVanC** [umputun/remark42#1163] [Q&A] [answered]
The page I'm using for testing is https://bbaovanc.com/blog/the-redesign-of-my-website/.

### Chrome and Firefox

Both OAuth and anonymous work properly.

### Safari

If I sign in with GitHub, then it just doesn't sign in at all (it opens the GitHub OAuth page, but then when it closes and goes back to Remark, it's still not signed in). If I try signing in as anonymous, then it appears to work, but I get a big red banner that says "Not authorized." when I try and send a comment. If I reload the page, I'm not signed in

### Safari, Firefox, and Chrome

Signing in with GitHub gives a "{"error":"failed to get token"}" response on the callback URL. Signing in as anonymous works fine, and I can send messages properly.

## My configs

```yaml
version: '3'

services:
  remark:
    image: umputun/remark42:master
    restart: always
    environment:
      - REMARK_URL=https://remark.boba.best
      - SITE=bbaovanc.com,boba.best,remark
      - ALLOWED_HOSTS=remark.boba.best bbaovanc.com boba.best
      - SECRET
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - ADMIN_SHARED_ID=github_4cb43a41df2719c23f1aafc06d7a844288354217,email_3a84cbdb570d38d183c1d046e08974e15a2a156a
      - ADMIN_PASSWD
      - ADMIN_SHARED_EMAIL=bbaovanc@bbaovanc.com
      - AUTH_SAME_SITE=none
      #- AUTH_SEND_JWT_HEADER=true
      - AUTH_ANON=true
      - VOTES_IP=true
      - ANON_VOTE=true
      - AUTH_GITHUB_CID
      - AUTH_GITHUB_CSEC
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_FROM=remark@boba.best
      - SMTP_HOST=mail.boba.best
      - SMTP_PORT=465
      - SMTP_TLS=true
      - SMTP_USERNAME=remark@boba.best
      - SMTP_PASSWORD
      - NOTIFY_EMAIL_FROM=remark@boba.best
      - NOTIFY_ADMINS=email
      - NOTIFY_USERS=email
    volumes:
      - ./data/remark/var:/srv/var
    ports:
      - 127.0.0.1:86:8080
```

Caddy config:

```
# vim: ft=caddyfile

remark.boba.best {
    encode zstd gzip
    import hsts
    import log

    reverse_proxy localhost:86 {
        header_up X-Real-IP {remote_host}
    }

    import basicerrors
}
```
