### DISCUSSION TITLE
Install on OpenLiteSpeed via Docker - curl 127.0.0.1 fails

### DISCUSSION THREAD

**Discussion by dayeggpi** [umputun/remark42#1389] [Q&A]
hi team,

I have have the instructions and followed all the steps.
Remark42 is installed via docker, but I fail to access it.

This is my setup:
Server Ubuntu 20.04 TLS
OpenLiteSpeed
Docker is installed

Here are all the steps I did : 

1- I created a file docker-compose.yml with this content, and I saved it under `/home/{MYDOMAIN.COM}/public_html/remark42`

```yaml
version: '2'

services:
    remark:
        build: .
        image: umputun/remark42:latest
        container_name: "remark42"
        hostname: "remark42"
        restart: always
        
        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
 
        # uncomment to expose directly (no proxy)
        ports:
          - "8080:8080"

        environment:
            - REMARK_URL=https://{MYDOMAIN.COM}
            - SECRET=********   # here I put my root password
            - SITE={mydomain}
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - DEBUG=true
            - AUTH_ANON=true
            # - ADMIN_PASSWD=password
        volumes:
            - ./var:/srv/var
```

For now I want to try out the simple config, no facebook/github etc.

Then I do : 

`$ docker pull umputun/remark42:latest`
`$ docker-compose pull`
`$ docker-compose up -d`

Now a `$ docker stats` gives me : 

> CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
82f7486d2a00   remark42   0.00%     9.488MiB / 3.746GiB   0.25%     4.74kB / 839B   4.1kB / 26.9MB   9

and 

`$ docker ps -a` gives me : 

> CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
82f7486d2a00   umputun/remark42:latest   "/init.sh /srv/remar…"   28 minutes ago   Up 28 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   remark42

Now in OpenLiteSpeed, I did `$ sudo nano /usr/local/lsws/conf/httpd_config.conf` and added : 

> extprocessor remark42 {
  type                    proxy
  address                 127.0.0.1:8080
  maxConns                100
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

as described here https://community.cyberpanel.net/t/reverse-proxy-traffic-to-docker-container-on-cyberpanel/30644

This by the way also appears on OpenLiteSpeed frontend as such : 
![OLSreverse](https://user-images.githubusercontent.com/11727370/173188282-7714b89c-4770-4a16-8438-d339d28df1e0.png)

Then, in `/home/{MYDOMAIN.COM}/public_html/` I added the following in .htaccess : 

> RewriteCond %{HTTPS} !=on
RewriteCond %{REQUEST_URI} =/remark42/*
REWRITERULE ^(.*)$ http://remark42:8080/$1 [P]

I tried with the following as well btw but it breaks all the frontend, so I stick with the above : 
> #RewriteCond %{HTTPS} !=on
#RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
#RewriteRule ^(.*)$ http://remark42/$1 [P]

After I rebooted OpenLiteSpeed, my website works, but when doing `$ curl 127.0.0.1:8080` I get 
> curl: (56) Recv failure: Connection reset by peer

If i do 
`$ docker exec -it remark42 /bin/sh`, then inside `/srv #` I run `curl -v 127.0.0.1:8080`
I get:
> Trying 127.0.0.1:8080...
> Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.80.0
> Accept: */*

.....

then 404 page not fount at the end`

If i do `iptables -L | grep -i docker` I get some results with DOCKER, but the DOCKER-INGRESS bock is missing in the iptables output.

So I have no idea what to do now...
Any help would be gladly welcome :) 
Note that I am really a noob...

Thanks in advance !
