### ISSUE TITLE
Verified user icon is broken

### ISSUE THREAD

**Issue by T1MOXA** [umputun/remark42#1180]
![image](https://user-images.githubusercontent.com/19938629/142449334-41b25578-83c5-4624-8e06-f96f3bb725d2.png)
Here is fixed verison

```css
.comment__verification_active{
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBmaWxsPSIjNGZiYmQ2IiBkPSJtNS44MjMgMTQuODIyLTEuMjguMjA2YS44MjQuODI0IDAgMCAxLS45LS41MmwtLjQ2My0xLjIxMmEuODI0LjgyNCAwIDAgMC0uNDc2LS40NzZsLTEuMjEyLS40NjJhLjgyNC44MjQgMCAwIDEtLjUyLS45bC4yMDYtMS4yODFhLjgyNC44MjQgMCAwIDAtLjE3NS0uNjVMLjE4NSA4LjUyYS44MjQuODI0IDAgMCAxIDAtMS4wNGwuODE4LTEuMDA2YS44MjQuODI0IDAgMCAwIC4xNzUtLjY1TC45NzIgNC41NDJhLjgyNC44MjQgMCAwIDEgLjUyLS45bDEuMjEyLS40NjNhLjgyNC44MjQgMCAwIDAgLjQ3Ni0uNDc2bC40NjItMS4yMTJhLjgyNC44MjQgMCAwIDEgLjktLjUybDEuMjgxLjIwNmEuODI0LjgyNCAwIDAgMCAuNjUtLjE3NUw3LjQ4LjE4NWEuODI0LjgyNCAwIDAgMSAxLjA0IDBsMS4wMDYuODE4YS44MjQuODI0IDAgMCAwIC42NS4xNzVsMS4yODEtLjIwNmEuODI0LjgyNCAwIDAgMSAuOS41MmwuNDYzIDEuMjEyYy4wODQuMjIuMjU3LjM5Mi40NzYuNDc2bDEuMjEyLjQ2MmMuMzY1LjE0LjU4Mi41MTUuNTIuOWwtLjIwNiAxLjI4MWEuODI0LjgyNCAwIDAgMCAuMTc1LjY1bC44MTggMS4wMDdhLjgyNC44MjQgMCAwIDEgMCAxLjA0bC0uODE4IDEuMDA2YS44MjQuODI0IDAgMCAwLS4xNzUuNjVsLjIwNiAxLjI4MWEuODI0LjgyNCAwIDAgMS0uNTIuOWwtMS4yMTIuNDYzYS44MjQuODI0IDAgMCAwLS40NzYuNDc2bC0uNDYyIDEuMjEyYS44MjQuODI0IDAgMCAxLS45LjUybC0xLjI4MS0uMjA2YS44MjQuODI0IDAgMCAwLS42NS4xNzVsLTEuMDA3LjgxOGEuODI0LjgyNCAwIDAgMS0xLjA0IDBsLTEuMDA2LS44MThhLjgyNC44MjQgMCAwIDAtLjY1LS4xNzV6Ii8+PHBhdGggc3Ryb2tlPSIjRkZGIiBzdHJva2Utd2lkdGg9IjEuNiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNNC43NTUgOC4yNTIgNyAxMC41bDQuNDk1LTQuNDk1Ii8+PC9nPjwvc3ZnPg==)
}
```

or html version:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><g fill="none" fill-rule="evenodd"><path fill="#4fbbd6" d="m5.823 14.822-1.28.206a.824.824 0 0 1-.9-.52l-.463-1.212a.824.824 0 0 0-.476-.476l-1.212-.462a.824.824 0 0 1-.52-.9l.206-1.281a.824.824 0 0 0-.175-.65L.185 8.52a.824.824 0 0 1 0-1.04l.818-1.006a.824.824 0 0 0 .175-.65L.972 4.542a.824.824 0 0 1 .52-.9l1.212-.463a.824.824 0 0 0 .476-.476l.462-1.212a.824.824 0 0 1 .9-.52l1.281.206a.824.824 0 0 0 .65-.175L7.48.185a.824.824 0 0 1 1.04 0l1.006.818a.824.824 0 0 0 .65.175l1.281-.206a.824.824 0 0 1 .9.52l.463 1.212c.084.22.257.392.476.476l1.212.462c.365.14.582.515.52.9l-.206 1.281a.824.824 0 0 0 .175.65l.818 1.007a.824.824 0 0 1 0 1.04l-.818 1.006a.824.824 0 0 0-.175.65l.206 1.281a.824.824 0 0 1-.52.9l-1.212.463a.824.824 0 0 0-.476.476l-.462 1.212a.824.824 0 0 1-.9.52l-1.281-.206a.824.824 0 0 0-.65.175l-1.007.818a.824.824 0 0 1-1.04 0l-1.006-.818a.824.824 0 0 0-.65-.175z"/><path stroke="#FFF" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" d="M4.755 8.252 7 10.5l4.495-4.495"/></g></svg>
```
![image](https://user-images.githubusercontent.com/19938629/142450387-7bc3b8f0-03f8-4482-b471-bf9d03f7f2f4.png)
