### ISSUE TITLE
Admin password required for backup command?

### ISSUE THREAD

**Issue by nununo** [umputun/remark42#1363]
Hello,

I feel like I'm probably missing something simple here.

I have been using remark42 for a while now and everything is working fine. But now I finally decided to take care of automating backups/restores and am running into an issue:

When I try to run this command:
```bash
docker exec -it remark42 backup -s mysite
```

It says that mandatory parameter `--admin-passwd` is missing.

I assumed I didn't need an admin password in my production instance since in the [docs](https://remark42.com/docs/getting-started/installation/) it is said:
> make sure you don't keep ADMIN_PASSWD=something... for any non-development deployments
But now it seems it is required by the backup command.

Anyway, I updated my `docker-compose.yml` to include an admin password and yet, when I tried to pass it to the command, I am getting a 401 Unauthorized error.

Here's my `docker-compose.yml`:

```yaml
version: '3.4'

networks:
  traefik:
    external:
      name: traefik

services:
  remark:
    image: umputun/remark42:v1.9.0
    container_name: remark42
    hostname: remark42
    restart: always
    networks:
    - traefik
    environment:
    - TIME_ZONE=Europe/Lisbon
    - REMARK_URL=https://redacted
    - SECRET=${REMARK42_SECRET}
    - SITE=redacted
    - STORE_BOLT_PATH=/srv/var/db
    - BACKUP_PATH=/srv/var/backup
    - NOTIFY_ADMINS=email
    - NOTIFY_USERS=email
    - NOTIFY_EMAIL_FROM=redacted
    - ADMIN_SHARED_EMAIL=redacted
    - SMTP_HOST=smtp.sendgrid.net
    - SMTP_PORT=465
    - SMTP_TLS=true
    - SMTP_USERNAME=apikey
    - SMTP_PASSWORD=${REMARK42_SMTP_PASSWORD}
    - SMTP_TIMEOUT=60
    - AUTH_EMAIL_ENABLE=true
    - AUTH_EMAIL_FROM=redacted
    - AUTH_GITHUB_CID=${REMARK42_AUTH_GITHUB_CID}
    - AUTH_GITHUB_CSEC=${REMARK42_AUTH_GITHUB_CSEC}
    - AUTH_GOOGLE_CID=${REMARK42_AUTH_GOOGLE_CID}
    - AUTH_GOOGLE_CSEC=${REMARK42_AUTH_GOOGLE_CSEC}
    - ADMIN_PASSWD=${REMARK42_ADMIN_PASSWORD}
    - ADMIN_SHARED_ID=github_redacted
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - data:/srv/var
    labels:
      - traefik.enable=true
      - traefik.http.services.remark42.loadbalancer.server.port=8080
      - traefik.http.routers.remark42.rule=Host(`redacted`)
      - traefik.http.routers.remark42.entrypoints=redacted
      - traefik.http.routers.remark42.tls=true
      - traefik.http.routers.remark42.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik

volumes:
  data:
```

All the referenced environment variables are in a `remark42.env` file next to `docker-compose.yml`.

I'm sure I'm missing something simple but I don't know what it is. Please advise.

Thanks in advance.

Regards.
