### ISSUE TITLE
Telegram QR is not legible

### ISSUE THREAD

**Issue by Darkyenus** [umputun/remark42#1622]
With dark theme, the QR code is not easily scannable due to two problems:
![image](https://user-images.githubusercontent.com/5280068/231517524-0c414f2b-3929-46c4-8c29-fe8c4cef7a11.png)

1. The QR code is not square because of the CSS class (this is not a problem for scanning, just ugly)
```CSS
.N_Q {
  display: block;
  margin: 12px auto;
  width: 75%;
}
```

2. (the important one) The QR code has no border, which is mandatory by the QR code specification, likely removed by #1276

Browser: Firefox 111, Windows
