### ISSUE TITLE
README on how I really did development

### ISSUE THREAD

**Issue by patarapolw** [umputun/remark42#737]
Shouldn't it be told to do something like this?

```sh
# if you mainly work on backend
cp compose-dev-backend.yml compose-private-backend.yml
# if you mainly work on frontend
cp compose-dev-frontend.yml compose-private-frontend.yml

# And edit / debug `compose-private-*.yml` to your heart's content.
```

This is just because `compose-private-*.yml` are gitignored. As a matter of fact, my `compose-private-frontend.yml` contains this line.

```yaml
services:
    remark42:
        ...
        image: patarapolw/remark42:rev1
```

And, I pushed the image to Docker Hub, for deployment on VPS, to test that it really works.
